version: '3'
services:
  traefik:
    restart: unless-stopped
    image: traefik:v3.0
    ports:
      - '443:443'
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml

  chatmastr:
    image: ghcr.io/ryuumax/chatmastr:master
    networks:
      - traefik
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatmastr.rule=Host(`a100.rc.th-b.com`) && PathPrefix(`/chatmastr`)
      - traefik.http.services.home.loadbalancer.server.port=8501
    volumes:
      - /home/user/chatmastr/KnowledgeBase:/KnowledgeBase/
networks:
  traefik:
    external: true